import { db } from '@/db';
import { donations } from '@/db/schema';

async function main() {
    const now = new Date();
    const getDateOffset = (daysOffset: number) => {
        const date = new Date(now);
        date.setDate(date.getDate() + daysOffset);
        return date.toISOString();
    };

    const sampleDonations = [
        // Cooked meals (3)
        {
            donorId: 1,
            foodType: 'cooked',
            title: 'Fresh Vegetable Biryani',
            quantity: 50,
            unit: 'servings',
            expiryDate: getDateOffset(1),
            pickupLocation: 'Taj Palace Hotel, Colaba, Mumbai',
            description: 'Freshly prepared vegetable biryani from our lunch buffet. Contains rice, mixed vegetables, and aromatic spices.',
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
            aiCategory: 'human',
            aiConfidence: 0.92,
            status: 'available',
            isRecurring: false,
            distance: 3.5,
            createdAt: getDateOffset(-1),
            updatedAt: getDateOffset(-1),
        },
        {
            donorId: 2,
            foodType: 'cooked',
            title: 'Dal Tadka with Rice',
            quantity: 80,
            unit: 'servings',
            expiryDate: getDateOffset(0),
            pickupLocation: 'ITC Grand Bharat, Gurgaon, Delhi',
            description: 'Traditional yellow dal tadka served with steamed basmati rice. Nutritious and wholesome.',
            imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
            aiCategory: 'human',
            aiConfidence: 0.89,
            status: 'claimed',
            isRecurring: true,
            distance: 7.2,
            createdAt: getDateOffset(-2),
            updatedAt: getDateOffset(-0.5),
        },
        {
            donorId: 1,
            foodType: 'cooked',
            title: 'Mixed Vegetable Curry',
            quantity: 35,
            unit: 'servings',
            expiryDate: getDateOffset(-1),
            pickupLocation: 'Leela Palace, Andheri, Mumbai',
            description: 'Leftover mixed vegetable curry from evening banquet. Contains potatoes, carrots, beans, and peas.',
            imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe',
            aiCategory: 'human',
            aiConfidence: 0.87,
            status: 'completed',
            isRecurring: false,
            distance: 5.8,
            createdAt: getDateOffset(-5),
            updatedAt: getDateOffset(-4),
        },
        // Packaged foods (3)
        {
            donorId: 2,
            foodType: 'packaged',
            title: 'Sealed Biscuit Packets',
            quantity: 100,
            unit: 'items',
            expiryDate: getDateOffset(30),
            pickupLocation: 'Parle Factory Outlet, Vile Parle, Mumbai',
            description: 'Factory-sealed biscuit packets. Variety includes glucose, cream, and marie biscuits.',
            imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35',
            aiCategory: 'human',
            aiConfidence: 0.95,
            status: 'available',
            isRecurring: true,
            distance: 4.3,
            createdAt: getDateOffset(-3),
            updatedAt: getDateOffset(-3),
        },
        {
            donorId: 1,
            foodType: 'packaged',
            title: 'Instant Noodles Cartons',
            quantity: 60,
            unit: 'items',
            expiryDate: getDateOffset(45),
            pickupLocation: 'Big Bazaar Warehouse, Whitefield, Bangalore',
            description: 'Bulk instant noodles in sealed packaging. Various flavors available.',
            imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624',
            aiCategory: 'human',
            aiConfidence: 0.91,
            status: 'in_transit',
            isRecurring: false,
            distance: 9.1,
            createdAt: getDateOffset(-4),
            updatedAt: getDateOffset(-1),
        },
        {
            donorId: 2,
            foodType: 'packaged',
            title: 'Canned Vegetables Mix',
            quantity: 40,
            unit: 'items',
            expiryDate: getDateOffset(90),
            pickupLocation: 'Metro Cash & Carry, Rajouri Garden, Delhi',
            description: 'Assorted canned vegetables including corn, peas, and mixed vegetables.',
            imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04',
            aiCategory: 'animal',
            aiConfidence: 0.82,
            status: 'claimed',
            isRecurring: false,
            distance: 6.7,
            createdAt: getDateOffset(-2),
            updatedAt: getDateOffset(-1),
        },
        // Produce (2)
        {
            donorId: 1,
            foodType: 'produce',
            title: 'Fresh Seasonal Vegetables',
            quantity: 25,
            unit: 'kg',
            expiryDate: getDateOffset(3),
            pickupLocation: 'APMC Market, Vashi, Mumbai',
            description: 'Mix of fresh vegetables including tomatoes, onions, potatoes, and leafy greens.',
            imageUrl: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d',
            aiCategory: 'animal',
            aiConfidence: 0.88,
            status: 'available',
            isRecurring: true,
            distance: 11.5,
            createdAt: getDateOffset(-1),
            updatedAt: getDateOffset(-1),
        },
        {
            donorId: 2,
            foodType: 'produce',
            title: 'Ripe Bananas',
            quantity: 15,
            unit: 'kg',
            expiryDate: getDateOffset(2),
            pickupLocation: 'Spencer\'s Hypermarket, Indiranagar, Bangalore',
            description: 'Slightly overripe bananas, perfect for immediate consumption or animal feed.',
            imageUrl: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224',
            aiCategory: 'animal',
            aiConfidence: 0.93,
            status: 'in_transit',
            isRecurring: false,
            distance: 8.3,
            createdAt: getDateOffset(-2),
            updatedAt: getDateOffset(-0.5),
        },
        // Bakery (2)
        {
            donorId: 1,
            foodType: 'bakery',
            title: 'Assorted Bread Loaves',
            quantity: 30,
            unit: 'items',
            expiryDate: getDateOffset(1),
            pickupLocation: 'Monginis Bakery, Bandra West, Mumbai',
            description: 'Mix of white and brown bread loaves from today\'s production.',
            imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
            aiCategory: 'human',
            aiConfidence: 0.94,
            status: 'available',
            isRecurring: false,
            distance: 2.1,
            createdAt: getDateOffset(-0.5),
            updatedAt: getDateOffset(-0.5),
        },
        {
            donorId: 2,
            foodType: 'bakery',
            title: 'Leftover Pastries and Cakes',
            quantity: 20,
            unit: 'items',
            expiryDate: getDateOffset(-2),
            pickupLocation: 'Theobroma, Khan Market, Delhi',
            description: 'Day-old pastries and cake slices. Suitable for animal shelters.',
            imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
            aiCategory: 'animal',
            aiConfidence: 0.86,
            status: 'cancelled',
            isRecurring: false,
            distance: 4.9,
            createdAt: getDateOffset(-6),
            updatedAt: getDateOffset(-5),
        },
        // Dairy (2)
        {
            donorId: 1,
            foodType: 'dairy',
            title: 'Fresh Paneer Blocks',
            quantity: 10,
            unit: 'kg',
            expiryDate: getDateOffset(4),
            pickupLocation: 'Mother Dairy Booth, Koramangala, Bangalore',
            description: 'Fresh paneer blocks, sealed and refrigerated.',
            imageUrl: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da',
            aiCategory: 'human',
            aiConfidence: 0.97,
            status: 'claimed',
            isRecurring: false,
            distance: 5.4,
            createdAt: getDateOffset(-3),
            updatedAt: getDateOffset(-2),
        },
        {
            donorId: 2,
            foodType: 'dairy',
            title: 'Yogurt Containers',
            quantity: 50,
            unit: 'items',
            expiryDate: getDateOffset(5),
            pickupLocation: 'Amul Store, Dadar, Mumbai',
            description: 'Individual yogurt containers, various flavors.',
            imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777',
            aiCategory: 'human',
            aiConfidence: 0.85,
            status: 'in_transit',
            isRecurring: false,
            distance: 7.8,
            createdAt: getDateOffset(-4),
            updatedAt: getDateOffset(-1),
        },
        // Other (3)
        {
            donorId: 1,
            foodType: 'other',
            title: 'Mixed Dry Fruits',
            quantity: 12,
            unit: 'kg',
            expiryDate: getDateOffset(60),
            pickupLocation: 'Khari Baoli Market, Old Delhi, Delhi',
            description: 'Bulk dry fruits including almonds, cashews, and raisins.',
            imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32',
            aiCategory: 'animal',
            aiConfidence: 0.81,
            status: 'available',
            isRecurring: false,
            distance: 10.2,
            createdAt: getDateOffset(-2),
            updatedAt: getDateOffset(-2),
        },
        {
            donorId: 2,
            foodType: 'other',
            title: 'Leftover Rice Grains',
            quantity: 40,
            unit: 'kg',
            expiryDate: getDateOffset(7),
            pickupLocation: 'Community Kitchen, Jayanagar, Bangalore',
            description: 'Excess raw rice from community kitchen supplies.',
            imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c',
            aiCategory: 'animal',
            aiConfidence: 0.89,
            status: 'completed',
            isRecurring: false,
            distance: 6.1,
            createdAt: getDateOffset(-7),
            updatedAt: getDateOffset(-6),
        },
        {
            donorId: 1,
            foodType: 'other',
            title: 'Cooking Oil Bottles',
            quantity: 25,
            unit: 'items',
            expiryDate: getDateOffset(120),
            pickupLocation: 'Reliance Fresh, Powai, Mumbai',
            description: 'Sealed cooking oil bottles, various brands and types.',
            imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5',
            aiCategory: 'human',
            aiConfidence: 0.98,
            status: 'claimed',
            isRecurring: false,
            distance: 12.0,
            createdAt: getDateOffset(-5),
            updatedAt: getDateOffset(-4),
        },
    ];

    await db.insert(donations).values(sampleDonations);
    
    console.log('✅ Donations seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});